kristijanhusak/vim-dadbod-ui

doc/dadbod-ui.txt
doc/dadbod-ui.txt has a duplicate tag, namely "vim-dadbod-ui". I changed the first instance (in the first line) to "dadbod-ui.txt" (the name of the file) which seems to be the convention for help files.
=> Rename duplicate tag in help file.

doc/dadbod-ui.txt
It's a small change, but I fixed it.
The key in `g:db_ui_icons` was duplicated, so it was removed.
Thank you.
=> [Doc] Remove duplicate key

autoload/db_ui/drawer.vim, plugin/db_ui.vim
Add icon for database type. it depends on `nerdfonts`,The default value is `0`, set to `1` means enable it.
```
let g:dbui_show_database_icon= 0
```
Sorry to bother you, I messed up `git rebase` and had to re-clone and commit.
=> add icon for database type

autoload/db_ui/table_helpers.vim
Fixed SQL Server table helpers for foreign keys and references.
=> Fixed SQL Server tables helpers

autoload/db_ui/schemas.vim
In the case of Windows, the `systemlist()` result contains a CR (`\r`) at the end, so I trim it.
Before:
After:
Thank you!
=> Fix to get schema info correctly on Windows

README.md
Just noticed that `g:db_ui_disable_mappings` was improperly named in the README with a hyphen instead of an underscore, causing syntax errors when sourcing the change.
=> Update README "disable mappings" variable name

autoload/db_ui/drawer.vim
The previous fix only covered one row, generating up to 3 table entries in the drawer.
Now, the drawer will also handle (i.e.) 12 tables correctly.
=> Fix issue with more than one row of sqlite tables

autoload/db_ui/dbout.vim, plugin/db_ui.vim
Allow yanking of column names in the dbout windows using `yh` mapping.
Rather than try complicated templates for insert, select, update etc its probably more useful to just be able to use the column names from a query in whatever context you like. I've added a mapping `yh` to be able to yank the headers from the dbout window.
=> Dbout window column name yanking.

autoload/db_ui.vim, autoload/db_ui/dbout.vim, autoload/db_ui/schemas.vim, autoload/db_ui/table_helpers.vim
This PR adds first-class support for Oracle databases to this plugin. Here's what works:
* Table helpers.
* Schema detection.
* Table detection.
Here's what isn't working:
* Jumping to foreign keys inside of a `dbout` buffer.
Here's a screenshot:
If there are any requests for edits I'll be happy to take a look. Additionally, I'll get to work on creating a public oracle database so that this PR can be tested.
=> Improved Oracle Support

autoload/db_ui/schemas.vim
Hello,
I love this plugin, I use it for my everyday job and has made me my life easier.
Recently I was creating a new personal user in a Redshift cluster, and found out this:
Seems that the schemas for the newly created user are missing, checking with my good old user I saw that the schemas in fact were there:
Both users has the same permissions and belong to the same groups, so I found out that the query to get the schemas was the one making the difference, it seems a issue related with the `information_schema` and `public` permissions, here is a nice explanation:
https://stackoverflow.com/questions/21781952/how-to-check-if-postgresql-public-schema-exists
In my particular case the problem is that Redshift is based on PostgreSQL 8.0.2, and as the same documentation says, the 
table …
=> query schemas on pg_catalog.pg_namespace

autoload/db_ui/schemas.vim
I have to query from a few Oracle Data Warehouses for work, where all the client accounts only have access to specific views, not to any actual tables. I'd love to use dadbod-ui for this, but the current setup only lists tables under each schema in the drawer.
This patch adds views to the list of tables in the `oracle_schemes_table_query`, similar to how the `postgres` scheme. The `UNION` of `ALL_VIEWS` and `ALL_TABLES` is done in a subquery to simplify the handling of the join on the `ALL_USERS` table.
=> Add Views to scheme tables query for Oracle

README.md
I am using this plugin for some time and I can confirm that works nicely on Windows (10 and 11).
So I think that this TODO can be removed. I just noticed that.
**ping** @kristijanhusak Thanks for the amazing plugin! :)
=> update readme since this plugin works on windows

autoload/db_ui.vim, autoload/db_ui/drawer.vim
...because they pain me in the form of hit-enter-prompts :(
resolves #198
=> fix: remove seemingly innocuous echoes

autoload/db_ui/schemas.vim, autoload/db_ui/table_helpers.vim
- This PR adds support for BigQuery, an OLAP database provided by Google, as a BigQuery adapter was recently added to `vim-dadbod` with https://github.com/tpope/vim-dadbod/pull/125
- This PR adds functionality for `bigquery:://` connections
- The new adapter depends on having the `bq` CLI provided by the google cloud CLI is in the user's `$PATH`, configured to authenticate with some google identity credentials
- As such, running & testing this requires installing the `gcloud` CLI ([installation instructions](https://cloud.google.com/sdk/docs/install)) and having a google account. (Users interested in using `vim-dadbod-ui` for running queries against BigQuery will almost surely have `gcloud` and `bq` installed already)
- I've added a global variable `g:db_adapter_bigquery_region`, to allow …
=> Add support for vim-dadbod BiqQuery adapter

autoload/db_ui/drawer.vim, autoload/db_ui/query.vim
I feel like this should not be forced on the buffers created by this plugin, and should instead be set up by the user in their configs. I don't use this option, and have to use a major hack to turn it off:
```lua
vim.api.nvim_create_autocmd("BufEnter", {
pattern = "*-query-*",
group = vim.api.nvim_create_augroup("DadbodCursorlineHack", { clear = true }),
callback = function()
vim.defer_fn(function()
vim.opt_local.cursorline = false
end, 50)
end,
desc = "Disable cursorline in dbui",
})
```
Closes #217
=> Remove cursorline option

autoload/db_ui/table_helpers.vim
Most of the other adapter types have a "Columns" helper, but not sqlite, so this PR adds it.
=> Add Columns helper for sqlite

README.md, autoload/db_ui/schemas.vim, autoload/db_ui/table_helpers.vim, doc/dadbod-ui.txt, plugin/db_ui.vim
Pull request adds support for a `vim.g.db_ui_use_redshift` flag that you can add to init.lua or, in my case, plug-dadbod.lua. New code just checks for the existence of this new flag and if it is not present or is set to 0 it runs the original code. 
I have also updated the README with the vimL way of adding this flag.
This would close #131
=> Added Support for Redshift

README.md, autoload/db_ui/dbout.vim, doc/dadbod-ui.txt, plugin/db_ui.vim
Another customization I've made is to show full minutes and seconds on query execute. This would be a completely new feature but it's something I use so I thought I'd put it into a pull request in case you'd like to merge it.
All it does is adjust the screen to show the full time of your query rather than only the seconds.
<details>
<Summary> Examples:</Summary>
Less than 10 seconds into the query:
Less than 1 minute into the query:
Less than 1 minute and 10 seconds into the query:
Less than 2 minutes into the query:
Less than 2 minutes and 10 seconds into the query:
More than 2 minutes and 10 seconds into the query:
</details>
=> Show Full Minutes and Seconds on Query Execute

README.md
Since I suffered from a a severe case of tunnel vision on #259, I think a reference to all the docs in the existing `Settings` section of the README would help.
=> Add settings reference to README

autoload/db_ui/schemas.vim
The number of tables / schemas fetched from the BigQuery adapter is limited to 100 by default, which caused my database to randomly skip some tables / schemas when syncing. 
With this change I Increase this number to a big enough number so that all tables / schemas are included.
=> fix(bigquery): Increase the number of schemas / tables fetched to 100000

plugin/db_ui.vim
Some adapters output a blank line as the first line of the `dbout` buffer, e.g. `oracle` with `sqlplus`. In this situation, an error is currently thrown on each execution, as the `FileType dbout` auto-command calls `normal!zo` with the cursor on the first line, which is not in a fold.
This PR simply suppresses that error with `:silent!`
=> Suppress "No fold found" with :silent!

autoload/db_ui/notifications.vim
I encountered an issue with [mini.notify](https://github.com/echasnovski/mini.notify):
```
Error detected while processing function <SNR>79_method[2]..60[30]..63[7]..34[16]..function <SNR>79_method[2]..60[30]..63[7]..34[15]..db_ui#notifications#error[1]..<SNR>83_notification[11]. .<SNR>83_notification_nvim_notify: line 7: E5108: Error executing lua (mini.notify) Only valid values of vim.log.levels are supported. stack traceback: [C]: in function 'error' ...ack/myNeovimPackages/start/mini.nvim/lua/mini/notify.lua:839: in function 'error' ...ack/myNeovimPackages/start/mini.nvim/lua/mini/notify.lua:305: in function 'notify' [string "luaeval()"]:1: in main chunk
```
The error was caused by `mini.notify` not using accepted values from …
=> fix(notifications): use `vim.log.levels`

autoload/db_ui/schemas.vim
I had some problems where the SQLCL binary was named 'sqlcl' instead of 'sql' which caused some issues with parsing the response, since the default is to expect data in SQLPlus's format.
=> feat(oracle): check dbext_default_ORA_bin as  'sql' or 'sqlcl'

autoload/db_ui/query.vim
Concerns
--------
* This is a bit beyond what you suggested but I thought it'd be useful for people who prefer line-wrapping (for example).
Description
-----------
Resolves #267.
~~~diff
commit 296374af294d41a2ea15017adb9c2ee146ee5f6c
Author: ss-raicangu <ssCm181126@outlook.com>
Date:   2024-08-07T23:07:24+12:00
refactor: set `filetype` after other options
This allows filetype plugins, such as `mysql.vim`, to override any of
the special query buffer settings if needed.
A similar pattern of setting `filetype` before other settings is present
for the DBUI drawer. I assume this is more deliberate, and is out of
scope for kristijanhusak/vim-dadbod-ui#267, so I haven't changed this
part.
This change was not signed off, so might be reverted.
BREAKING-CHANGE: Options set in filetype plugins are …
=> fix: stop overriding `list` in query files

autoload/db_ui/table_helpers.vim
The current Primary Keys table helper for Postgres doesn't list primary keys as expected because it joins against `information_schema.referential_constraints`, which only has foreign keys.
To reproduce:
1. Spin up the current stable version of PostgreSQL (16.3).
2. Create a table with a primary key:
```sql
CREATE TABLE pk_test (
id INT,
name TEXT,
PRIMARY KEY (id)
);
```
3. Run the existing Primary Keys table helper and see that the primary key is not listed.
<hr>
This PR fixes the Primary Keys table helper by simply querying against `information_schema.table_constraints`. It also renames `basic_constraint_query` to indicate it should only be used for foreign key queries.
=> fix(postgres): Primary Keys table helper

autoload/db_ui/drawer.vim, doc/dadbod-ui.txt, plugin/db_ui.vim, test/test-drawer-sections.vim
Fixes https://github.com/kristijanhusak/vim-dadbod-ui/issues/299 and then some.
Thank you for creating this wonderful plugin, and thanks in advance for considering my changes.
=> feat: Add configurable drawer sections with custom order

ftplugin/dbout.vim, plugin/db_ui.vim
an ftplugin setting is overridable by the user through after/ftplugin.
i actually couldn't find a way to override the foldmethod at all without that change (maybe it's posisble, but i couldn't find a way). With this change, it's trivial: i just set the foldmethod in my ftplugin/after...
i'm using dadbod to query json (both in postgresql and jq), and i can have much better folding than what dadbod-ui can offer me out of the box. but i need control for that...
thanks for great plugins!
=> dbout: set foldmethod in ftplugin instead of ft autocommand
